import Header from "./components/Header"

import "@/styles/tailwind.css"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const RootLayout = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<Header />
				<main className="mt-24 px-4">{children}</main>
			</body>
		</html>
	)
}

export default RootLayout

